lgandx/Responder

- settings.py
I've been working on running Responder on Android ([link](https://github.com/nvssks/Android-Responder)), in general this works without any issues with the exception of the patched part in the settings.py file. Reason is that some linux commands, flags and/or files are not available, mainly in older Android versions.
> Patch for Android 4.x terminals that are missing some linux commands

- tools/MultiRelay.py
**Problem**
On macOS hosts, the `TCP_KEEPIDLE` is not exported for python. Running `MultiRelay.py` on macOS hosts would crash when trying to connect to a target host as a result.
```
----------------------------------------
Exception happened during processing of request from ('x.x.x.x', xxxxx)
Traceback (most recent call last):
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
self.process_request(request, client_address)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
self.finish_request(request, client_address)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in …
```
> Check if the platform is macOS before setting TCP_KEEPIDLE

- Responder.py
- servers/HTTP.py
1.  	0e3e6f9
The HTTP and HTTPS modules were crashing when using Responder in a real-world scenario. It turned out that the above mentioned modules recv function were implemented in the good hopes that a simple call to socket.recv(N) will actually receive N bytes of data (or the full header). However this is not always the case.
> http://man7.org/linux/man-pages/man2/recv.2.html 
> The receive calls normally return any data available, up to the requested amount, rather than waiting for receipt of the full amount requested.
2.  	2c32704
As the HTTP class is technically the same as the HTTPS class (since the SSL wrapping happens in Responder.py). If you decide to keep it the original way, please share a reason I'm interested.
> Fixing HTTP header issue

- settings.py
Current build is failing on a new build of Kali2 as ifconfig and netstat commands appear to be removed:
```
Traceback (most recent call last):
File "Responder.py", line 56, in <module>
settings.Config.populate(options)
File "/pentest/Responder/settings.py", line 247, in populate
RoutingInfo = subprocess.check_output(["netstat", "-rn"])
File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```
Added in additional processing for `ip` commands:
```
ip address show
ip route show
```
> added `ip` commands in addition to ifconfig and netstat

- README.md
- Responder.py
- servers/MSSQL.py
When connecting to a named instance, a SQL client (at least SQL Server Native Client) will send a request (namely a `CLNT_UCAST_INST` message) to the server's SQL Server Browser service for instance connection information. If it gets no response, the connection attempt fails.
By adding a SQL Server Browser responder for these requests, we ensure that connections are successfully made to the SQL Server responder for hash capture.
As per the comment, this is based on the document "[[MC-SQLR]: SQL Server Resolution Protocol](https://msdn.microsoft.com/en-us/library/cc219703.aspx)".
Run the following VBScript which attempts to connect to named instance `INSTANCE` on (presumably) non-existent host `DOESNOTEXIST`:
```vbscript
CreateObject("ADODB.Connection").Open "Provider=SQLNCLI11;Data …
```
> Add Microsoft SQL Server Browser responder

- servers/LDAP.py
Recent changes that support random challenges missed one case where the `Challenge` value needed to passed in to the `ParseLDAPHash` function. This PR contains a 2-line changes that fixes this and prevents the program from failing in this case.
> Pass Challenge value to the LDAP parsing function

- servers/HTTP_Proxy.py
I fixed problem for inject html when "body" is write in upper case or body appear in file js.
Sincerely,
Lionel
> Add ignore case on check body for html inject

- tools/FindSMB2UPTime.py
Hey,
I just noticed there was a space typo in the FindSMB2UPTime.py script.
This was the error:
`  File "tools/FindSMB2UPTime.py", line 42`
`    print "DC is up since:", t[1]`
`IndentationError: unindent does not match any outer indentation level`
It looks like it was introduced in the commit 5859c31e8ecf35c5b12ac653e8ab793bc9270604 on 28 Jun.
Best regards.
> Fixed space typo in FindSMB2UPTime.py

- tools/RunFinger.py
Hey there,
This change just fixes the MS17-010 check. There's a small typo that outputs the result as MS10-010. I also changed "Os" to "OS" a couple of lines down.
> Fixed some small typos in MS17-010 output

- tools/FindSMB2UPTime.py
Hey,
I changed a few things in FindSMB2UPTime.py including:
- Support for subnets
- Multiprocessing
- Error handling when the host in unreachable
- Timeout parameter is now taken into account. It was previously defined **after** the connexion attempt.
Regards.
> FindSMB2UPTime.py : Subnet support, error handling, minor improvements

- servers/HTTP.py
If the client keeps the connection open after receiving the HTTP response, the response will be sent several times. Proof is that in the output we can see many:
> [HTTP] Sending NTLM authentication request to xxxx
This PR fixes this.
Thanks to @skelsec who wrote this part of the code for the fix suggestion!
> Fix multi HTTP responses

- tools/MultiRelay/RelayMultiCore.py
Currently, MultiRelay allows either to forward authentications for `ALL` users, or for a predefined set of users, but there is no way to specify users for which authentication should not be forwarded. This PR allows this by prepending a `!` to the unwanted user names, like `-u ALL -u '!someuser'`.
> [MultiRelay] allow to blacklist users

- servers/HTTP.py
Remaining size should be checked at the end of the loop, the current implementation hang when POST request Content-Lenght is 0.
We want to check for Content-Length header only if we received full header.
> Fix socket timeout on HTTP POST requests

- tools/FindSMB2UPTime.py
I've encountered cases where a server doesn't disclose its boot time (the ServerStartTime field is all zeros).
In this case, the current FindSMB2UPTime returns nothing (since `time.strftime('%Y-%m-%d %H:%M:%S')` triggers an exception for dates before 1900, and 0 means Windows Epoch in 1601).
With this patch, this case is properly handled. For example:
```
Server x.x.x.a did not disclose its boot time
Server x.x.x.b doesn't support SMBv2
Server x.x.x.c is up since: 2019-01-25 15:57:18
```
> FindSMB2UPTime: properly deal with servers not disclosing their boot time

- tools/RunFinger.py
Change the usage of "is" to "==" to comply with the new syntax warnings found in python >= 3.8
Observed warnings:
RunFinger.py:61: SyntaxWarning: "is" with a literal. Did you mean "=="?
if PY2OR3 is "PY2":
RunFinger.py:68: SyntaxWarning: "is" with a literal. Did you mean "=="?
if PY2OR3 is "PY2":
RunFinger.py:74: SyntaxWarning: "is" with a literal. Did you mean "=="?
if PY2OR3 is "PY2":
> Alter "is" to "==" for Python 3.8 compatibility

- Responder.py
Responder doesn't correctly bind to the given network interface and hogs the ports it uses across all interfaces leading to conflicts (i.e. I have a host with a web server on eth1 and can't run Responder there on eth0). This patch just uses the `settings.Config.Bind_To` variable as the bind address rather than relying on `SO_BINDTODEVICE` which hogs ports when the address is `''` or `0.0.0.0` (at least on Ubuntu 18.04 and Kali Linux where I tested this).
> Use settings.Config.Bind_To as bind address.

- tools/MultiRelay.py
- tools/MultiRelay/RelayMultiCore.py
- tools/MultiRelay/RelayMultiPackets.py
- tools/RunFingerPackets.py
- tools/SMBFinger/Finger.py
`==` should be used when comparing values, `is` should be used to compare identities.
Modern versions of Python throw a SyntaxWarning, that's what made me notice this when updating.
> Compare values with `==` instead of `is`

- README.md
- Responder.py
New version of Responder does not have the -r flag anymore. I updated the README and the --help flags to reflect that.
> Updated the README and Responder help flags

- utils.py
Line 512 should read:
print(' %-27s' % "DCE-RPC server" + (enabled if settings.Config.DCERPC_On_Off else disabled))
Instead of:
print(' %-27s' % "DCE-RPC server" + (enabled if settings.Config.RDP_On_Off else disabled))
> DE-RPC server status not correct

- odict.py
and was removed from collections in newer versions of python
this change works in python 3.10.2 on manjaro linux
> MutableMapping was moved to collections.abc

- tools/odict.py
cf. https://github.com/BlackArch/blackarch/issues/3344
fix #172
cf. https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections#answer-70870087
> odict: fix import issue

- utils.py
If `CaptureMultipleHashFromSameHost = On` (the default), then Responder would log the first captured hash/cleartext twice for each unique `(<module>, <type>, <client>, <user> [, <cleartext>])` tuple.
> Fix double logging of first hash/cleartext when CaptureMultipleHashFromSameHost = On

- Responder.conf
- Responder.py
- servers/SNMP.py
- settings.py
- utils.py
All community strings are logged as they are sent to the server. This initial implementation only supports SNMPv1 and SNMPv2c.
`pyasn1` is required for this server to function.
> Implement a basic SNMP listener

- Responder.conf
- poisoners/LLMNR.py
- settings.py
The `ExpandIpRanges` in `settings.py` did not handle IPv6 addresses. Added additional logic that function which:
- Identifies IPv6 vs IPv4 address
- Pads/expands shortened IPv6 addresses to ease iterating a known length
- Iterates through the a provided range in a similar fashion to an IPv4 address
- Shortens the IPv6 address to match with the system will see
Also updated `Responder.conf` in include IPv6 examples for the `RespondTo` and `DontRespondTo` options as wells as including a note that, for systems with both and IPv4 and IPv6 address, BOTH addresses must be included in the `DontRespondTo` option in order to be effective.
> Allowing IPv6 addresses in RespondTo and DontRespondTo 

- settings.py
Added full path to gen-self-sign-cert.sh during initialization to fix #212 where certificates are not generated due to the relative path.
> Added full path to gen-self-sign-cert.sh

- packets.py
`ServerType` is misspelled as `ServerTlype`
> fix typo of ServerTlype

- servers/SNMP.py
It was a great addition in #218 to support SNMP (https://zxsecurity.co.nz/research/insights/run-zero-credentials-capture/ awesome work!). This PR implements the support for SNMPv3 that was still outstanding.
This is the current output for SNMPv3, SNMPv1 and SNMPv2c:
The output for SNMPv3 hash can be formatted easily for later cracking, for example with Hashcat. There is a [gist](https://gist.github.com/lowSoA/267538e0c2b82ea0281ba7ba9f01182a) which eases this process (with an included hash example from this PR).
**Note:** as in the original PR #218, `pyasn1` is required. Tested with `pyasn1==0.4.8`  in case it can be added to `requirements.txt`.
> Implement SNMPv3 support

- servers/MSSQL.py
- servers/SMB.py
- tools/MultiRelay/RelayMultiCore.py
- tools/RunFinger.py
- tools/SMBFinger/Finger.py
Fix the bug identified in https://github.com/lgandx/Responder/issues/223 where comparisons with single bytes breaks in python3 in some cases.
For further details see the linked issue.
> Fix bug with single byte comparisons in python3

- .gitignore
- servers/HTTP.py
- HTTP basic auth credentials of the form `user:password:with:colons` can now be parsed correctly (fixes #255)
- added a further commit to ignore `.pyc` files and generated certificates
> Fixed parsing of HTTP basic auth containing colons

- servers/SMTP.py
Without this responder silently fails. During debugging I observed [[[can only concatenate str (not "bytes") to str]]] error. Enabling decoding of bytes made the error disappear and credentials properly intercepted (on-screen stdout, logs and to DB).  Thank you for a very useful tool :)
> Fixing soft failure which results in missed SMTP credential interception

- tools/MultiRelay/odict.py
- tools/SMBFinger/odict.py
This pull request aims at keeping the same import for non-deprecated python versions (up to 3.6) and improve the import for later versions.
```
/Responder/tools/SMBFinger/odict.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
from collections import MutableMapping as DictMixin
```
See https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections for reference
> Upgrading `collections` import

- servers/MSSQL.py
There was a bytes vs string issue in the `MSSQLBrowser` class which resulted in `TypeError: a bytes-like object is required, not 'str'`.
fixes #251
> Fixed a TypeError in MSSQLBrowser

- Responder.conf
- Responder.py
- settings.py
I recently had a coworker ask how they could disable NBTNS poisoning specifically, and since the only way to do that was to modify the code, I thought, why not add in the option to do it in the config?
Specifically:
```ini
[Responder Core]
; Poisoners to start
MDNS  = On
LLMNR = On
NBTNS = On
; Servers to start
SQL      = On
... etc
```
> Add options for poisoners

- Responder.py
- poisoners/LLMNR.py
- poisoners/MDNS.py
- poisoners/NBTNS.py
- settings.py
- utils.py
MDE seems to detect the TTL value when responder sends the poisoned request. Without playing the cat and mouse, this PR allows the TTL value to be controlled from the configuration file and by default the value will be random within a defined range.
> Random TTL value added to avoid some EDR detections

- README.md
- Responder.py
- poisoners/LLMNR.py
- settings.py
The present pull requests adds the `-N` (`--AnswerName`) flag to Responder, which allows to spoof the answer name returned by LLMNR responses when poisoning a client. This is mainly useful when attempting to perform Kerberos relaying over HTTP.
More details on the motivation behind this pull request can be found in the following article (should be published on 27th january):
https://synacktiv.com/publications/abusing-multicast-poisoning-for-pre-authenticated-kerberos-relay-over-http-with
> Adding answer name spoofing capabilities to LLMNR poisoner for Kerberos relaying purposes

- poisoners/DHCP.py
Hey, thanks for the great tool!
Recently I ran into #181 and #304 during DHCP poisoning.
As far as I understand the code, it currently breaks when the IP address contains an `E`, `O` or `F` since it prematurely terminates the IP address' bytes. (Instead of checking for the end-of-input, as I'm assuming was the intent)
This commit should resolve those issues since it always takes the four bytes required for an IPv4 address.
It also operates directly on the bytes and avoids an additional encoding/decoding round-trip.
> DHCP poisoner: refactor FindIP

- README.md
- Responder.py
- servers/SMB.py
- settings.py
Hello!
In [this recent article](https://www.synacktiv.com/publications/taking-the-relaying-capabilities-of-multicast-poisoning-to-the-next-level-tricking), Synacktiv demonstrated that during multicast poisoning, depending on the error code returned by the SMB server at the end of the authentication process, it was possible to force the target machine to authenticate via WebDAV, if the WebClient service was running.
This PR adds a new option, `-E, --ErrorCode`, that permits to switch from the default `STATUS_ACCESS_DENIED`, to `STATUS_LOGON_FAILURE`.
> Add control on the status code returned by the SMB server
